= Changelog

All notable changes to this project will be documented in this file.

== Unreleased

=== Upcoming

A future v2 release will be coming out and changing some return types. Namely, functions
that are returning a single item list will be changed to returning the single item in the list.
For example, `NodePing.Checks.find_by_id/2` returns the check with the ID, but in a list, so you
have to proceed with a following `List.first/1` to get the map.

There will likely also be some upcoming improvements changes as the library is reviewed.

== 2022-11-09 v1.6.0

=== Added

* PostgreSQL check added: https://nodeping.com/pgsql_check.html
* Typespecs added to checktypes

=== Changed

* MySQL check updated: https://nodeping.com/mysql_check.html

=== Fixed

* Some check types were missing some fields. They have been corrected.

== 2022-10-06 v1.5.0

=== Added

* MTR check added: https://nodeping.com/mtr_check.html
* Redis check added: https://nodeping.com/redis_check.html

== 2022-03-24 v1.4.0

=== Added

* Added support for the notifications profile feature: https://nodeping.com/docs-api-notificationprofiles.html

== 2021-12-01 v1.3.0

=== Changed

* Added `transport` to the SIP checktype. Set `false` for both TCP/UDP, `"udp"` for UDP, and `"tcp"` for TCP

== 2021-10-08 v1.2.3

=== Added

* Support added for muting checks and contacts as per the 2021-10-07 NodePing API changelog
* Some Additions to the README
* typespecs added in the `NodePing.Checks` module

=== Changed

* All defstruct modules had the moduledoc changed to false to clean up the documentation page. The moduledocs
were previously just copy/paste from NodePing's check definitions and can be found there for each check type.

== 2021-08-25 v1.2.2

=== Added

Added the `autodiagnotifications` option to account creation and updates, defaulting
to `false`.

== 2021-08-25 v1.2.1

=== Added

* Support for autodiag by setting `:autodiag => true` in your check args

=== Fixed

* Increase timeout for diagnostics to 60 seconds from the default 5 seconds so the diagnostic doesn't timeout each time.

== 2021-06-01 v1.2.0

=== Added

* Oldest verison supported is 1.10
* Updated httpoison to version 1.8

=== Fixed

* Manually specify `:target` for the `snmp.ex` checktype

== 2021-05-18 v1.1.4

=== Added

* `dnssection argument added to `NodePing.Checks.Dns` checktype with a default value of "answer"

== 2021-02-19 v1.1.3

=== Added

* `sendheaders` optional argument for `NodePing.Checks.HttpParse` checktype

== 2021-02-16 v1.1.2

=== Added

* `ipv6` flag for DoH/DoT checktype

== 2021-02-04 v1.1.1

=== Added

* Added the new DoH/DoT checktype

=== Fixed

* Fixed some functions that had a default value of `nil` where it should have been an empty list
  ** These `opt` names were changed to `opt` for clarity
  ** Similar fix for `NodePing.Checks.disable_all_checks` by combining `customerid` into `opts`
* Some clarity added to the docs (namely that `opts` is a list of tuples)

== 2020-09-15 v1.1.0

=== Added

* Functionality added to the NodePing API on https://nodeping.com/docs-api-changes.html[2020-09-14]
	** New function `NodePing.Checks.get_many` and `NodePing.Checks.get_many!`
	** Uptime functionality added to all the `NodePing.Checks` get functions
	** offset opt added to `NodePing.Results.get_results`
	** Added events function `NodePing.Results.get_events`
* Added module docs to the checktypes in `NodePing.Checktypes`

=== Fixed

* Some of the get functions in `NodePing.Checks` wouldn't return a tuple like one might expect with `:ok` or `:error`. This was fixed and the proper ! identifier functions were added.
* `NodePing.Helpers.merge_querystrings` ignores `nil` values

